---
- name: Clean git dir
  file:
    state: absent
    path: "/tmp/coins/"

- git:
    repo: 'https://github.com/ilya-dubovskiy/coins-devops-challenge.git'
    dest: /tmp/coins

- name: remove all the old crap
  command: docker system prune -a -f
  become: yes

- name: start minikube
  command: minikube start --vm-driver=none
  become: yes
  ignore_errors: yes

- name: Create a Deployment by reading the definition from a local file
  k8s_raw:
    state: present
    src: /tmp/coins/kubernetes-deployments/django-todo.deployment
